### ISSUE TITLE
Running continuously on runpod.io 

### ISSUE THREAD

**Issue by kithmina-siriwardana** [blib-la/runpod-worker-comfy#15]
When I deployed the provide image "timpietruskyblibla/runpod-worker-comfy:latest" in the runpod.io it works fine. But I tried downloading the github repo and built an image using docker and push it to the my own docker hub (public repo) without making any changes to the repo, then it is not working. There are no any errors in building or pushing to the docker hub or when running in the runpod.io. But the thing is when I send a request, it is processing continuously. It doesn't provide any errors if I send incorrect data as the input (eg: an incorrect checkpoint name) or it doesn't get completed, if I set all data correctly in the request. Please help me out. Thanks.

my docker image: kithminasiriwardana13/worker-comfy:dev

**Comment by IT21020230** [comment]
It may not be a bug in the repo, I am new to these and I don't know how to create an issue correctly. So sorry for that.

**Comment by TimPietrusky** [comment]
@kithmina-siriwardana thanks for creating the issue! And don't worry, it's a first time for everything. 

Can you please let me know which command you executed? And what the error was that you saw?

**Comment by TimPietrusky** [comment]
@kithmina-siriwardana have you ever resolved the issue? 

Because when I think about this again, it might be that you have not added `--platform linux/amd64` when building the image. But this is a wild guess. 

I'm closing the issue for now, but please feel free to open it again if there is still a problem that we need to solve. Please feel also free to join our Discord to get direct help in the support channel.
